id: Transformer-En2Vi-NoPE-WordPiece
seed: 2104
pretrained_path: null
model:
    d_model: 512
    d_ffn: 2048
    n_layer: 6
    n_head: 8
    max_len: 256
    dropout: 0.1
    share_emb_emb: False
    share_emb_prj: False
    emb_type: nope
    # xavier_init: True
trainer:
    nepochs: 50
    val_step: 1
    log_step: 1
    lr: !!float 1e-4
optimizer:
    patience: 10
    warmup: 10
    factor: 0.5
dataset:
    train:
        config:
            src_path: data/en-vi/raw-data/train/train.en
            trg_path: data/en-vi/raw-data/train/train.vi
            # token_type: bpe
            # src_vocab: ["vocab/english_bpe/en-bpe-minfreq5-vocab.json", "vocab/english_bpe/en-bpe-minfreq5-merges.txt"]
            # trg_vocab: ["vocab/vietnamese_bpe/vi-bpe-minfreq5-vocab.json", "vocab/vietnamese_bpe/vi-bpe-minfreq5-merges.txt"]
            # src_vocab: ["vocab/shared/shared-vocab.json", "vocab/shared/shared-merges.txt"]
            # trg_vocab: ["vocab/shared/shared-vocab.json", "vocab/shared/shared-merges.txt"]
            token_type: wordpiece
            src_vocab: vocab/english_word/en-wordpiece-minfreq5-vocab.txt
            trg_vocab: vocab/vietnamese_word/vi-wordpiece-minfreq5-vocab.txt
        batch_size: 16
        shuffle: True
        clip_grads: True
        num_workers: 4
    val:
        config:
            src_path: data/en-vi/raw-data/val/tst2012.en
            trg_path: data/en-vi/raw-data/val/tst2012.vi
            # token_type: bpe
            # src_vocab: ["vocab/english_bpe/en-bpe-minfreq5-vocab.json", "vocab/english_bpe/en-bpe-minfreq5-merges.txt"]
            # trg_vocab: ["vocab/vietnamese_bpe/vi-bpe-minfreq5-vocab.json", "vocab/vietnamese_bpe/vi-bpe-minfreq5-merges.txt"]
            # src_vocab: ["vocab/shared/shared-vocab.json", "vocab/shared/shared-merges.txt"]
            # trg_vocab: ["vocab/shared/shared-vocab.json", "vocab/shared/shared-merges.txt"]
            token_type: wordpiece
            src_vocab: vocab/english_word/en-wordpiece-minfreq5-vocab.txt
            trg_vocab: vocab/vietnamese_word/vi-wordpiece-minfreq5-vocab.txt
        batch_size: 16
        num_workers: 4
