id: Transformers-en-to-vi
seed: 2104
pretrained_path: null
model:
    d_model: 512
    d_ffn: 2048
    n_layer: 6
    n_head: 8
    max_len: 256
    dropout: 0.1
    share_emb_emb: True
    share_emb_prj: True
    xavier_init: True
trainer:
    nepochs: 50
    val_step: 1
    log_step: 1
    lr: !!float 1e-5
optimizer:
    patience: 10
    warmup: 10
    factor: 0.5
dataset:
    train:
        src_path: data/en-vi/raw-data/train/train.en
        trg_path: data/en-vi/raw-data/train/train.vi
        # src_vocab: ["vocab/english/english-vocab.json", "vocab/english/english-merges.txt"]
        # trg_vocab: ["vocab/vietnamese/vietnamese-vocab.json", "vocab/vietnamese/vietnamese-merges.txt"]
        src_vocab: ["vocab//english-vocab.json", "vocab/english/english-merges.txt"]
        trg_vocab: ["vocab/vietnamese/vietnamese-vocab.json", "vocab/vietnamese/vietnamese-merges.txt"]
        batch_size: 16
        shuffle: True
        clip_grads: False
        num_workers: 8
    val:
        src_path: data/en-vi/raw-data/val/tst2012.en
        trg_path: data/en-vi/raw-data/val/tst2012.vi
        # src_vocab: ["vocab/english/english-vocab.json", "vocab/english/english-merges.txt"]
        # trg_vocab: ["vocab/vietnamese/vietnamese-vocab.json", "vocab/vietnamese/vietnamese-merges.txt"]
        batch_size: 16
        num_workers: 8
